version: '2.1'

services:
  localstack:
    container_name: github-audit-logs-2-splunk-localstack 
    image: localstack/localstack:0.11.5
#    network_mode: bridge
    ports:
      # - "4567-4597:4567-4597"
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"
    environment:
      - SERVICES=iam,lambda,apigateway
      - DEFAULT_REGION=us-east-2
      #- LAMBDA_EXECUTOR=docker
      #- LAMBDA_REMOTE_DOCKER=1
      #- LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      #- DOCKER_HOST=unix:///var/run/docker.sock
      #- HOST_TMP_FOLDER=${TMPDIR}
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
